public class roster {
    // FIX ME: PAGE 7.10 FOR IDEAS ON ROSTER CONSTRUCTION
    // SORT ALPHABETICALLY, RATING, PLAYER COST, AND GOALS
    // PLAYERS WILL NEED TO BE ARRAYS TO HOLD ALL THAT INFORMATION
    // INSIDE OF A ROSTER ARRAY
    // ALSO ADD ABILITY TO TRADE PLAYERS BETWEEN TEAMS AND OUTPUT TEAM ROSTERS
    // SORTED WITH TOTAL COST OF TEAMS PLAYERS, AND TEAM RATING AVERAGE
    // MAYBE EVEN ADD ABILITY TO SORT PLAYERS BASED ON POSITION WITHIN THE ROSTER
    // THEMSELVES EX. DEFENCE, OFFENCE, MIDFIELDERS, GOALKEEPERS
}
